########################################################

# Rainbomizer - A (probably fun) Grand Theft Auto San Andreas Mod that
#               randomizes stuff
# Copyright (C) 2019 - Parik

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#######################################################

# General Configuration

Enabled   = true
Seed      = -1 # -1 for random

Unprotect = true
AutosaveSlot = 8 # Set it to a non-existant slot (eg. -1 or 9) to disable

#######################################################
# Traffic Randomizer
[TrafficRandomizer]

Enabled = true

# This will make a specific vehicle spawn on streets
ForcedVehicleEnabled = false
ForcedVehicleID = 500

EnableTrains = true
EnableBoats = true
EnableAircrafts = true
EnableCars = true
EnableBikes = true
EnableTrailers = true

# For special vehicles on street that can't spawn peds
DefaultModel = 0

#######################################################
[CarColRandomizer]

Enabled = true
Exceptions = [0, 1] # These colours will not be randomized

#######################################################
[PoliceHeliRandomizer]
Enabled = true

#######################################################
[CheatRandomizer]

Enabled = true
EnableEasterEgg = true

#######################################################
# Experimental - Crashes are quite often
[HandlingRandomizer]

Enabled = false

#######################################################
[WeaponRandomizer]

Enabled = true
RandomizePlayerWeapons = true
SkipChecks = false # Checks related to weapons required for certain missions
                   # You might not be able to complete some missions
				   # without this enabled.

# Pattern checks
Patterns = [
	{ thread = "drugs4", ped = 0, weapon = 30, allowed = ["slot"]},
	{ thread = "finalec", ped = 0, weapon = 28, allowed = ["slot"]},
	{ thread = "drugs1", weapon = 28, allowed = ["slot"]},
	{ weapon = 43, allowed = [43]},
	{ weapon = 44, allowed = [44, 45]},
	{ thread = "sweet1", weapon = 41, allowed = [41]},
	{ thread = "heist5", weapon = 38, allowed = ["slot"]},
	{ thread = "zero1", weapon = 38, allowed = ["slot"]},
	{ thread = "casino6", weapon = 37, allowed = [37]},
	{ thread = "casino6", weapon = 37, allowed = [37]},
	{ thread = "shrange", allowed = ["slot"]},
	{ thread = "truth2", weapon = 37, allowed = [37]},
	{ thread = "truth2", weapon = 35, allowed = [35, 36, 38]},
	{ thread = "des10", ped = 0, allowed = [28, 32]},
	{ thread = "casino9", weapon = 22, allowed = [22, 23, 24]}
]

#######################################################
[PickupsRandomizer]

Enabled = true
ReplaceWithWeaponsOnly = true # Does nothing yet

#######################################################
[ParkedCarRandomizer]

Enabled = true
RandomizeFixedSpawns = true
RandomizeRandomSpawns = true

#######################################################
[LicensePlateRandomizer]

Enabled = true

#######################################################
[SoundsRandomizer] # Random Dialogues for now

Enabled = true
MatchSubtitles = true
AudioEventsFile = "data/AudioEvents.txt" # Relative to game directory
ForceAudioLineEnabled = false
ForceAudioLine = 0

#######################################################
[ScriptVehicleRandomizer]

Enabled = true
SkipChecks = false  # Don't enable this if you don't want to softlock every
                    # other mission :P

