########################################################

# Rainbomizer - A (probably fun) Grand Theft Auto San Andreas Mod that
#               randomizes stuff
# Copyright (C) 2019 - Parik

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#######################################################

# General Configuration

Enabled = true
Seed    = -1 # -1 for random

#######################################################
# Traffic Randomizer
[TrafficRandomizer]

Enabled = true

# This will make a specific vehicle spawn on streets
ForcedVehicleEnabled = false
ForcedVehicleID = 500

EnableTrains = true
EnableBoats = true
EnableAircrafts = true
EnableCars = true
EnableBikes = true
EnableTrailers = true

# For special vehicles on street that can't spawn peds
DefaultModel = 0

#######################################################
[CarColRandomizer]

Enabled = true
Exceptions = [0, 1] # These colours will not be randomized

#######################################################
[PoliceHeliRandomizer]
Enabled = true

#######################################################
[CheatRandomizer]

Enabled = true
EnableEasterEgg = true

#######################################################
# Experimental - Crashes are quite often
[HandlingRandomizer]

Enabled = false

#######################################################
[WeaponRandomizer]

Enabled = false
RandomizePlayerWeapons = true
SkipChecks = false # Checks related to weapons required for certain missions
                   # You might not be able to complete some missions
				   # without this enabled.

#######################################################
[ParkedCarRandomizer]

Enabled = true
RandomizeFixedSpawns = true
RandomizeRandomSpawns = true

#######################################################
[LicensePlateRandomizer]

Enabled = true

#######################################################
[SoundsRandomizer] # Random Dialogues for now

Enabled = true
MatchSubtitles = true
AudioEventsFile = "data/AudioEvents.txt" # Relative to game directory

#######################################################
[ScriptVehicleRandomizer]

Enabled = true
SkipChecks = false  # Don't enable this if you don't want to softlock every
                    # other mission :P

